# main_ch2ch_trans_s01_moco

config:
  FEATURE_EXTRACTION: False
  FEATURE_EXTRACT: Trunk
  ID: 1
  TAG: main_ch2ch_trans_s01_moco
  VERBOSE: False
  LOG_FREQUENCY: 30
  TEST_ONLY: False
  TEST_MODEL: False
  SEED_VALUE: 0
  MULTI_PROCESSING_METHOD: forkserver
  MONITOR_PERF_STATS: True
  PERF_STAT_FREQUENCY: 10
  ROLLING_BTIME_FREQ: 10
  DATA:
    NUM_DATALOADER_WORKERS: 6
    NUM_OF_SURGICAL_TOOLS: 7
    NUM_CLASSES_PHASE: 7
    LABEL_TOOL_OR_PHASE: Phase
    TRAIN:
      DATA_PATHS: [./datasets/cholec80/labels/train/5fps_100_0.pickle]
      DATA_SOURCES: [disk_filelist_surgery]
      DATASET_NAMES: [surgery_datasets]
      BATCHSIZE_PER_REPLICA: 64
      LABEL_TYPE: sample_index
      TRANSFORMS:
        - name: Resize
          size: [252, 448]
        - name: ImgPilToMultiCrop
          total_num_crops: 2
          size_crops: [224, 224]
          num_crops: [1, 1]
          crop_scales: [[0.5, 1], [0.5, 1]]
        - name: RandAugmentSurgery
          magnitude: 8.0
          magnitude_std: 0.5
          transforms: ['SharpnessIncreasing', 'AutoContrast', 'Equalize', 'ColorIncreasing', 'ContrastIncreasing', 'BrightnessIncreasing', 'Rotate', 'ShearX', 'ShearY', 'TranslateXRel', 'TranslateYRel']
        - name: ColorJitter
          brightness: 0.4
          contrast: 0.4
          saturation: 0.4
        - name: RandomHorizontalFlip
        - name: ToTensor
        - name: RandomErasing
          p: 0.8
          scale: [0.02, 0.1]        
        - name: Normalize
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
      COLLATE_FUNCTION: multicrop_moco_collator
      MMAP_MODE: True
      COPY_TO_LOCAL_DISK: False
      DATA_LIMIT: -1
      DROP_LAST: True
    TEST:
      DATA_PATHS: [./datasets/cholec80/labels/test/1fps.pickle]
      LABEL_PATHS: [./datasets/cholec80/labels/test/1fps.pickle]
      DATA_SOURCES: [disk_filelist_surgery]
      LABEL_SOURCES: [disk_filelist_surgery]
      DATASET_NAMES: [surgery_datasets]
      BATCHSIZE_PER_REPLICA: 64
      LABEL_TYPE: standard
      TRANSFORMS:
        - name: Resize
          size: [224, 399]
        - name: ToTensor
        - name: Normalize
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
      MMAP_MODE: True
      COPY_TO_LOCAL_DISK: False
      DATA_LIMIT: -1
      DROP_LAST: False
    VAL:
      DATA_PATHS: [./datasets/cholec80/labels/val/1fps.pickle]
      LABEL_PATHS: [./datasets/cholec80/labels/val/1fps.pickle]
      DATA_SOURCES: [disk_filelist_surgery]
      LABEL_SOURCES: [disk_filelist_surgery]
      DATASET_NAMES: [surgery_datasets]
      BATCHSIZE_PER_REPLICA: 64
      LABEL_TYPE: standard
      TRANSFORMS:    
        - name: Resize
          size: [224, 399]
        - name: ToTensor
        - name: Normalize
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
      MMAP_MODE: True
      COPY_TO_LOCAL_DISK: False
      DATA_LIMIT: -1
      DROP_LAST: False
  TRAINER:
    TRAIN_STEP_NAME: custom_train_step_surgery
  METERS:
    name: ""
  MODEL:
    TRUNK:
      NAME: resnet
      RESNETS:
        DEPTH: 50
        WIDTH_MULTIPLIER: 1
      REGNET:
        depth: 18
        w_0: 200
        w_a: 106.23
        w_m: 2.48
        group_width: 112
    HEAD:
      PARAMS: [
        ["mlp", {"dims": [2048, 2048], "use_bn": True, "use_relu": True, "skip_last_layer_relu_bn": False}],
        ["mlp", {"dims": [2048, 256]}],
        ["mlp", {"dims": [256, 4096]}],
      ]      
    SYNC_BN_CONFIG:
      CONVERT_BN_TO_SYNC_BN: True
      SYNC_BN_TYPE: apex
      GROUP_SIZE: -1
    AMP_PARAMS:
      USE_AMP: True
      AMP_TYPE: apex
    WEIGHTS_INIT:
      PARAMS_FILE: "./checkpoints/defaults/resnet_50/resnet50-19c8e357.pth"
      APPEND_PREFIX: "trunk._feature_blocks."
      SKIP_LAYERS: ["num_batches_tracked"]
      STATE_DICT_KEY_NAME: ""
  LOSS:
    name: moco_loss
    moco_loss:
      embedding_dim: 4096
      queue_size: 65536
      momentum: 0.999
      temperature: 0.2
  OPTIMIZER:
      name: sgd
      use_larc: True
      larc_config:
        clip: False
        trust_coefficient: 0.001
        eps: 0.00000001      
      weight_decay: 0.000001
      momentum: 0.9
      nesterov: False
      num_epochs: 60
      regularize_bn: True
      regularize_bias: True
      param_schedulers:
        lr:
          auto_lr_scaling:
            auto_scale: true
            base_value: 0.1
            base_lr_batch_size: 256
          name: composite
          schedulers:
            - name: linear
              start_value: 0.6
              end_value: 4.8
            - name: cosine
              start_value: 4.8
              end_value: 0.0000
          update_interval: step
          interval_scaling: [rescaled, fixed]
          lengths: [0.05, 0.95]
  DISTRIBUTED:
    BACKEND: nccl
    NUM_NODES: 1
    NUM_PROC_PER_NODE: 4
    INIT_METHOD: tcp
    RUN_ID: auto
  MACHINE:
    DEVICE: gpu
  CHECKPOINT:
    DIR: "runs/cholec80/pre_training/cholec_to_cholec/series_01/run_001/"
    AUTO_RESUME: True
    CHECKPOINT_FREQUENCY: 10
    OVERWRITE_EXISTING: False
  HOOKS:  
    TENSORBOARD_SETUP:
      USE_TENSORBOARD: True
      EXPERIMENT_LOG_DIR: "runs/cholec80/pre_training/cholec_to_cholec/series_01/run_001/"
      FLUSH_EVERY_N_MIN: 20
      LOG_PARAMS: True
      LOG_PARAMS_GRADIENTS: True
      LOG_PARAMS_EVERY_N_ITERS: -1
  RUN_DIR: "runs/cholec80/pre_training/cholec_to_cholec/series_01/run_001/"      
