# Extended MoCo training from checkpoint
# Based on: configs/config/hparams/surgvu/pre_training/moco.yaml

config:
  FEATURE_EXTRACTION: False
  ID: 1
  TAG: "surgvu_moco_extended_${oc.env:SLURM_JOB_ID,local}"
  VERBOSE: False
  LOG_FREQUENCY: 30
  TEST_ONLY: False
  TEST_MODEL: False
  SEED_VALUE: 0
  MULTI_PROCESSING_METHOD: forkserver
  MONITOR_PERF_STATS: True
  PERF_STAT_FREQUENCY: 10
  ROLLING_BTIME_FREQ: 10
  DATA:
    NUM_DATALOADER_WORKERS: 8  # Keep per GPU
    NUM_CLASSES_PHASE: 8
    LABEL_TOOL_OR_PHASE: Phase
    TRAIN:
      DATA_PATHS: ["/net/tscratch/people/plgjmachali/surgvu_data_sampled_03/train"]
      LABEL_PATHS: [/net/pr2/projects/plgrid/plgg_13/sources/SelfSupSurg/datasets/surgvu/labels/0_3fps/train.pkl]
      DATA_SOURCES: [disk_filelist_surgvu]
      LABEL_SOURCES: [disk_filelist_surgvu]
      DATASET_NAMES: [surgvu_dataset]
      BATCHSIZE_PER_REPLICA: 256  # Increased for 4 GPU setup
      LABEL_TYPE: sample_index
      TRANSFORMS:
        - name: CropSides
          crop_left: 200
          crop_right: 200
          crop_top: 50
          crop_bottom: 50
        - name: Resize
          size: 256
        - name: ImgPilToMultiCrop
          total_num_crops: 2
          size_crops: [224, 224]
          num_crops: [1, 1]
          crop_scales: [[0.5, 1], [0.5, 1]]
        - name: RandAugmentSurgery
          magnitude: 8.0
          magnitude_std: 0.5
          transforms: ['SharpnessIncreasing', 'AutoContrast', 'Equalize', 'ColorIncreasing', 'ContrastIncreasing', 'BrightnessIncreasing', 'Rotate', 'ShearX', 'ShearY', 'TranslateXRel', 'TranslateYRel']
        - name: ColorJitter
          brightness: 0.4
          contrast: 0.4
          saturation: 0.4
        - name: RandomHorizontalFlip
        - name: ToTensor
        - name: RandomErasing
          p: 0.8
          scale: [0.02, 0.1]        
        - name: Normalize
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
      COLLATE_FUNCTION: multicrop_moco_collator
      MMAP_MODE: True
      COPY_TO_LOCAL_DISK: False
      DATA_LIMIT: -1
      DROP_LAST: True
  METERS:
    name: ""
  MODEL:
    TRUNK:
      NAME: resnet
      RESNETS:
        DEPTH: 50
        WIDTH_MULTIPLIER: 1
    HEAD:
      PARAMS: [
        ["mlp", {"dims": [2048, 2048], "use_bn": True, "use_relu": True, "skip_last_layer_relu_bn": False}],
        ["mlp", {"dims": [2048, 256]}],
        ["mlp", {"dims": [256, 4096]}],
      ]      
    SYNC_BN_CONFIG:
      CONVERT_BN_TO_SYNC_BN: True
      SYNC_BN_TYPE: pytorch
      GROUP_SIZE: -1
    AMP_PARAMS:
      USE_AMP: True
      AMP_TYPE: pytorch
    # NO WEIGHTS_INIT - will use checkpoint instead
  LOSS:
    name: moco_loss
    moco_loss:
      embedding_dim: 4096
      queue_size: 65536
      momentum: 0.999
      temperature: 0.2
  OPTIMIZER:
      name: sgd
      use_larc: False
      larc_config:
        clip: False
        trust_coefficient: 0.001
        eps: 0.00000001      
      weight_decay: 0.000001
      momentum: 0.9
      nesterov: False
      num_epochs: 100  # Extended training: 100 -> 200 total epochs
      regularize_bn: True
      regularize_bias: True
      param_schedulers:
        lr:
          auto_lr_scaling:
            auto_scale: true
            base_value: 0.05  # Lower starting LR for resumed training
            base_lr_batch_size: 256
          name: composite
          schedulers:
            - name: linear
              start_value: 0.1  # Lower warmup
              end_value: 1.0    # Lower peak
            - name: cosine
              start_value: 1.0
              end_value: 0.001  # Not zero to avoid complete stop
          update_interval: step
          interval_scaling: [rescaled, fixed]
          lengths: [0.02, 0.98]  # Shorter warmup, longer cosine
  DISTRIBUTED:
    BACKEND: nccl
    NUM_NODES: 1
    NUM_PROC_PER_NODE: 4  # 4 GPU setup
    INIT_METHOD: tcp
    RUN_ID: auto
  MACHINE:
    DEVICE: gpu
  CHECKPOINT:
    DIR: "${SCRATCH}/surgvu_results/pretraining/moco_extended/job_${SLURM_JOB_ID:-local}"
    AUTO_RESUME: True
    CHECKPOINT_FREQUENCY: 10
    OVERWRITE_EXISTING: False
  HOOKS:  
    TENSORBOARD_SETUP:
      USE_TENSORBOARD: True
      EXPERIMENT_LOG_DIR: "${SCRATCH}/surgvu_results/pretraining/moco_extended/job_${SLURM_JOB_ID:-local}/tb_logs"
      FLUSH_EVERY_N_MIN: 20
      LOG_PARAMS: True
      LOG_PARAMS_GRADIENTS: True
      LOG_PARAMS_EVERY_N_ITERS: -1
  RUN_DIR: "${SCRATCH}/surgvu_results/pretraining/moco_extended/job_${SLURM_JOB_ID:-local}"