# surgvu_moco_finetuning_phase_12_0 (Fine-tuning with MoCo pre-trained weights)

config:
  FEATURE_EXTRACTION: False
  ID: 1
  TAG: surgvu_moco_finetuning_phase_12_0_${SLURM_JOB_ID:-local}
  VERBOSE: False
  LOG_FREQUENCY: 10
  TEST_ONLY: False
  TEST_MODEL: True
  TEST_EVERY_NUM_EPOCH: 1 # how often to test the model during training (in epochs) - validation
  FEATURE_EXTRACT: Head
  SEED_VALUE: 0
  MULTI_PROCESSING_METHOD: forkserver
  MONITOR_PERF_STATS: True
  PERF_STAT_FREQUENCY: 10
  ROLLING_BTIME_FREQ: 10
  DATA:
    NUM_DATALOADER_WORKERS: 6
    NUM_CLASSES_PHASE: 8
    LABEL_TOOL_OR_PHASE: Phase
    TRAIN:
      DATA_PATHS: ["/net/tscratch/people/plgjmachali/surgvu_data_sampled_03/train"]
      LABEL_PATHS: ["/net/pr2/projects/plgrid/plgg_13/sources/SelfSupSurg/datasets/surgvu/labels/0_3fps/train_12p5.pkl"]
      DATA_SOURCES: [disk_filelist_surgvu]
      LABEL_SOURCES: [disk_filelist_surgvu]
      DATASET_NAMES: [surgvu_dataset]
      BATCHSIZE_PER_REPLICA: 64
      LABEL_TYPE: standard
      TRANSFORMS:
        - name: CropSides
          crop_left: 200
          crop_right: 200
          crop_top: 50
          crop_bottom: 50
        - name: Resize
          size: 256
        - name: RandAugmentSurgery
          magnitude: 8.0
          magnitude_std: 0.5
          transforms: ['SharpnessIncreasing', 'AutoContrast', 'Equalize', 'ColorIncreasing', 'ContrastIncreasing', 'BrightnessIncreasing', 'Rotate', 'ShearX', 'ShearY', 'TranslateXRel', 'TranslateYRel']
        - name: ColorJitter
          brightness: 0.4
          contrast: 0.4
          saturation: 0.4
        - name: RandomHorizontalFlip
        - name: ToTensor
        - name: RandomErasing
          p: 0.8
          scale: [0.02, 0.1]
        - name: Normalize
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
      MMAP_MODE: True
      COPY_TO_LOCAL_DISK: False
      DATA_LIMIT: -1
      DROP_LAST: True
    VAL:
      DATA_PATHS: ["/net/tscratch/people/plgjmachali/surgvu_data_sampled_03/val"]
      LABEL_PATHS: ["/net/pr2/projects/plgrid/plgg_13/sources/SelfSupSurg/datasets/surgvu/labels/0_3fps/val.pkl"]
      DATA_SOURCES: [disk_filelist_surgvu]
      LABEL_SOURCES: [disk_filelist_surgvu]
      DATASET_NAMES: [surgvu_dataset]
      BATCHSIZE_PER_REPLICA: 64
      LABEL_TYPE: standard
      TRANSFORMS:
        - name: CropSides
          crop_left: 200
          crop_right: 200
          crop_top: 50
          crop_bottom: 50
        - name: Resize
          size: 256
        - name: ToTensor
        - name: Normalize
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
      MMAP_MODE: True
      COPY_TO_LOCAL_DISK: False
      DATA_LIMIT: -1
      DROP_LAST: False
    TEST:
      DATA_PATHS: ["/net/tscratch/people/plgjmachali/surgvu_data_sampled_03/test"]
      LABEL_PATHS: ["/net/pr2/projects/plgrid/plgg_13/sources/SelfSupSurg/datasets/surgvu/labels/0_3fps/test.pkl"]
      DATA_SOURCES: [disk_filelist_surgvu]
      LABEL_SOURCES: [disk_filelist_surgvu]
      DATASET_NAMES: [surgvu_dataset]
      BATCHSIZE_PER_REPLICA: 64
      LABEL_TYPE: standard
      TRANSFORMS:
        - name: CropSides
          crop_left: 200
          crop_right: 200
          crop_top: 50
          crop_bottom: 50
        - name: Resize
          size: 256
        - name: ToTensor
        - name: Normalize
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
      MMAP_MODE: True
      COPY_TO_LOCAL_DISK: False
      DATA_LIMIT: -1
      DROP_LAST: False
  METERS:
    names: [accuracy_list_meter]
    accuracy_list_meter:
      num_meters: 1
      topk_values: [1]
  MODEL:
    TRUNK:
      NAME: resnet
      RESNETS:
        DEPTH: 50
        WIDTH_MULTIPLIER: 1
    HEAD:
      PARAMS: [
        ["mlp", {"dims": [2048, 8]}]
      ]
    SYNC_BN_CONFIG:
      CONVERT_BN_TO_SYNC_BN: True
      SYNC_BN_TYPE: pytorch
      GROUP_SIZE: -1
    AMP_PARAMS:
      USE_AMP: True
      AMP_TYPE: pytorch
    WEIGHTS_INIT:
      PARAMS_FILE: "/net/tscratch/people/plgjmachali/surgvu_results/pretraining/moco/job_1942741_20251010_0629/model_final_checkpoint_phase99.torch"
      APPEND_PREFIX: ""
      REMOVE_PREFIX: ""
      SKIP_LAYERS: ["head"]  # Skip the MoCo head, keep only trunk weights
      STATE_DICT_KEY_NAME: "classy_state_dict"
  LOSS:
    name: cross_entropy_multiple_output_single_target
    cross_entropy_multiple_output_single_target:
      weight: [0.1837, 1.0780, 1.8447, 2.1849, 3.3616, 5.2008, 13.9199, 14.8251]
      ignore_index: -1
  OPTIMIZER:
      name: sgd
      weight_decay: 0.000001
      momentum: 0.9
      nesterov: False
      num_epochs: 120
      regularize_bn: True
      regularize_bias: True
      param_schedulers:
        lr:
          auto_lr_scaling:
            auto_scale: true
            base_value: 0.005
            base_lr_batch_size: 256
          name: composite
          schedulers:
            - name: linear
              start_value: 0.6
              end_value: 4.8
            - name: cosine
              start_value: 4.8
              end_value: 0.0000
          update_interval: step
          interval_scaling: [rescaled, fixed]
          lengths: [0.05, 0.95]
  DISTRIBUTED:
    BACKEND: nccl
    NUM_NODES: 1
    NUM_PROC_PER_NODE: 4
    INIT_METHOD: tcp
    RUN_ID: auto
  MACHINE:
    DEVICE: gpu
  CHECKPOINT:
    DIR: ""
    AUTO_RESUME: True
    CHECKPOINT_FREQUENCY: 10
    OVERWRITE_EXISTING: False
  HOOKS:
    TENSORBOARD_SETUP:
      USE_TENSORBOARD: True
      EXPERIMENT_LOG_DIR: "${SCRATCH}/surgvu_results/finetuning/moco_to_surgvu/series_01/test/phase/12/0/tb_logs_${SLURM_JOB_ID:-local}"
      FLUSH_EVERY_N_MIN: 20
      LOG_PARAMS: True
      LOG_PARAMS_GRADIENTS: True
      LOG_PARAMS_EVERY_N_ITERS: -1
  RUN_DIR: "${SCRATCH}/surgvu_results/finetuning/moco_to_surgvu/series_01/test/phase/12/0/run_${SLURM_JOB_ID:-local}"